// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_app/test/data/repositories/theme_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kanban_app/core/enums/TaskStatus.dart' as _i8;
import 'package:kanban_app/data/data_soruces/local/theme_local_data_source.dart'
    as _i4;
import 'package:kanban_app/domain/entities/tasks/task_entity.dart' as _i7;
import 'package:kanban_app/domain/entities/theme_entity.dart' as _i6;
import 'package:kanban_app/services/hive_service.dart' as _i2;
import 'package:logger/logger.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHiveService_0 extends _i1.SmartFake implements _i2.HiveService {
  _FakeHiveService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_1 extends _i1.SmartFake implements _i3.Logger {
  _FakeLogger_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i4.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HiveService get hiveService =>
      (super.noSuchMethod(
            Invocation.getter(#hiveService),
            returnValue: _FakeHiveService_0(
              this,
              Invocation.getter(#hiveService),
            ),
          )
          as _i2.HiveService);

  @override
  _i3.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_1(this, Invocation.getter(#logger)),
          )
          as _i3.Logger);

  @override
  _i5.Future<_i6.AppTheme> getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue: _i5.Future<_i6.AppTheme>.value(_i6.AppTheme.light),
          )
          as _i5.Future<_i6.AppTheme>);

  @override
  _i5.Future<void> setTheme(_i6.AppTheme? theme) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i6.AppTheme> watchTheme() =>
      (super.noSuchMethod(
            Invocation.method(#watchTheme, []),
            returnValue: _i5.Stream<_i6.AppTheme>.empty(),
          )
          as _i5.Stream<_i6.AppTheme>);

  @override
  _i5.Future<List<_i7.TaskEntity>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i5.Future<List<_i7.TaskEntity>>.value(
              <_i7.TaskEntity>[],
            ),
          )
          as _i5.Future<List<_i7.TaskEntity>>);

  @override
  _i5.Future<void> saveTasks(List<_i7.TaskEntity>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#saveTasks, [tasks]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addTask(_i7.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateTask(
    String? taskId, {
    _i8.TaskStatus? status,
    int? duration,
    String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTask,
              [taskId],
              {#status: status, #duration: duration, #content: content},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeKey, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
