// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_app/test/domain/usecases/usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanban_app/core/enums/TaskStatus.dart' as _i5;
import 'package:kanban_app/domain/entities/tasks/task_entity.dart' as _i2;
import 'package:kanban_app/domain/entities/theme_entity.dart' as _i7;
import 'package:kanban_app/domain/irepositories/i_task_repository.dart' as _i3;
import 'package:kanban_app/domain/irepositories/i_theme_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskEntity_0 extends _i1.SmartFake implements _i2.TaskEntity {
  _FakeTaskEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i3.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskEntity>> fetchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllTasks, []),
            returnValue: _i4.Future<List<_i2.TaskEntity>>.value(
              <_i2.TaskEntity>[],
            ),
          )
          as _i4.Future<List<_i2.TaskEntity>>);

  @override
  _i4.Future<_i2.TaskEntity> createTask({
    required String? content,
    _i5.TaskStatus? status,
    int? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [], {
              #content: content,
              #status: status,
              #duration: duration,
            }),
            returnValue: _i4.Future<_i2.TaskEntity>.value(
              _FakeTaskEntity_0(
                this,
                Invocation.method(#createTask, [], {
                  #content: content,
                  #status: status,
                  #duration: duration,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TaskEntity>);

  @override
  _i4.Future<void> updateTask({
    required String? taskId,
    String? content,
    _i5.TaskStatus? status,
    int? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [], {
              #taskId: taskId,
              #content: content,
              #status: status,
              #duration: duration,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IThemeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIThemeRepository extends _i1.Mock implements _i6.IThemeRepository {
  MockIThemeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.AppTheme> getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue: _i4.Future<_i7.AppTheme>.value(_i7.AppTheme.light),
          )
          as _i4.Future<_i7.AppTheme>);

  @override
  _i4.Future<void> setTheme(_i7.AppTheme? theme) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i7.AppTheme> watchTheme() =>
      (super.noSuchMethod(
            Invocation.method(#watchTheme, []),
            returnValue: _i4.Stream<_i7.AppTheme>.empty(),
          )
          as _i4.Stream<_i7.AppTheme>);
}
