// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_app/test/presentation/cubit/comment_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kanban_app/domain/entities/comments/comment_entity.dart' as _i3;
import 'package:kanban_app/domain/irepositories/i_comment_repository.dart'
    as _i2;
import 'package:kanban_app/domain/usecases/comments/create_comment.dart' as _i6;
import 'package:kanban_app/domain/usecases/comments/get_comments.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeICommentRepository_0 extends _i1.SmartFake
    implements _i2.ICommentRepository {
  _FakeICommentRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentEntity_1 extends _i1.SmartFake implements _i3.CommentEntity {
  _FakeCommentEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetComments].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetComments extends _i1.Mock implements _i4.GetComments {
  MockGetComments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICommentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ICommentRepository);

  @override
  _i5.Future<List<_i3.CommentEntity>> call(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [taskId]),
            returnValue: _i5.Future<List<_i3.CommentEntity>>.value(
              <_i3.CommentEntity>[],
            ),
          )
          as _i5.Future<List<_i3.CommentEntity>>);
}

/// A class which mocks [CreateComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateComment extends _i1.Mock implements _i6.CreateComment {
  MockCreateComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICommentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ICommentRepository);

  @override
  _i5.Future<_i3.CommentEntity> call({
    required String? taskId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#taskId: taskId, #content: content}),
            returnValue: _i5.Future<_i3.CommentEntity>.value(
              _FakeCommentEntity_1(
                this,
                Invocation.method(#call, [], {
                  #taskId: taskId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.CommentEntity>);
}
