// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_app/test/presentation/cubit/task_board_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:kanban_app/core/enums/TaskStatus.dart' as _i9;
import 'package:kanban_app/domain/entities/comments/comment_entity.dart' as _i5;
import 'package:kanban_app/domain/entities/tasks/task_entity.dart' as _i3;
import 'package:kanban_app/domain/irepositories/i_comment_repository.dart'
    as _i4;
import 'package:kanban_app/domain/irepositories/i_task_repository.dart' as _i2;
import 'package:kanban_app/domain/usecases/comments/create_comment.dart'
    as _i13;
import 'package:kanban_app/domain/usecases/comments/get_comments.dart' as _i12;
import 'package:kanban_app/domain/usecases/tasks/create_task.dart' as _i8;
import 'package:kanban_app/domain/usecases/tasks/delete_task.dart' as _i11;
import 'package:kanban_app/domain/usecases/tasks/get_tasks.dart' as _i6;
import 'package:kanban_app/domain/usecases/tasks/update_task.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeITaskRepository_0 extends _i1.SmartFake
    implements _i2.ITaskRepository {
  _FakeITaskRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskEntity_1 extends _i1.SmartFake implements _i3.TaskEntity {
  _FakeTaskEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeICommentRepository_2 extends _i1.SmartFake
    implements _i4.ICommentRepository {
  _FakeICommentRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentEntity_3 extends _i1.SmartFake implements _i5.CommentEntity {
  _FakeCommentEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTasks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTasks extends _i1.Mock implements _i6.GetTasks {
  MockGetTasks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeITaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ITaskRepository);

  @override
  _i7.Future<List<_i3.TaskEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i7.Future<List<_i3.TaskEntity>>.value(
              <_i3.TaskEntity>[],
            ),
          )
          as _i7.Future<List<_i3.TaskEntity>>);
}

/// A class which mocks [CreateTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTask extends _i1.Mock implements _i8.CreateTask {
  MockCreateTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeITaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ITaskRepository);

  @override
  _i7.Future<_i3.TaskEntity> call({
    required String? content,
    int? duration,
    _i9.TaskStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #content: content,
              #duration: duration,
              #status: status,
            }),
            returnValue: _i7.Future<_i3.TaskEntity>.value(
              _FakeTaskEntity_1(
                this,
                Invocation.method(#call, [], {
                  #content: content,
                  #duration: duration,
                  #status: status,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.TaskEntity>);
}

/// A class which mocks [UpdateTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTask extends _i1.Mock implements _i10.UpdateTask {
  MockUpdateTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeITaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ITaskRepository);

  @override
  _i7.Future<void> call({
    required String? taskId,
    String? content,
    _i9.TaskStatus? status,
    int? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #taskId: taskId,
              #content: content,
              #status: status,
              #duration: duration,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [DeleteTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTask extends _i1.Mock implements _i11.DeleteTask {
  MockDeleteTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeITaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ITaskRepository);

  @override
  _i7.Future<void> call(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [taskId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GetComments].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetComments extends _i1.Mock implements _i12.GetComments {
  MockGetComments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ICommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICommentRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.ICommentRepository);

  @override
  _i7.Future<List<_i5.CommentEntity>> call(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [taskId]),
            returnValue: _i7.Future<List<_i5.CommentEntity>>.value(
              <_i5.CommentEntity>[],
            ),
          )
          as _i7.Future<List<_i5.CommentEntity>>);
}

/// A class which mocks [CreateComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateComment extends _i1.Mock implements _i13.CreateComment {
  MockCreateComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ICommentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICommentRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.ICommentRepository);

  @override
  _i7.Future<_i5.CommentEntity> call({
    required String? taskId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#taskId: taskId, #content: content}),
            returnValue: _i7.Future<_i5.CommentEntity>.value(
              _FakeCommentEntity_3(
                this,
                Invocation.method(#call, [], {
                  #taskId: taskId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.CommentEntity>);
}
